/// Reference location, craft category, language, and artisan type data for onboarding.
class LocationData {
  static const List<String> craftCategories = [
    'Handloom',
    'Pottery',
    'Wood Craft',
    'Metal Craft',
    'Bamboo Craft',
    'Jewellery',
    'Painting',
    'Handicraft',
    'Woodwork',
    'Metalwork',
    'Other',
  ];

  static const List<String> preferredLanguages = [
    'Odia',
    'Hindi',
    'English',
    'Bengali',
    'Telugu',
    'Tamil',
    'Marathi',
    'Gujarati',
    'Kannada',
    'Other',
  ];

  static const List<String> artisanTypes = [
    'Individual',
    'SHG',
    'Cooperative',
    'Family Business',
    'Self-help group',
    'Small business',
    'Other',
  ];

  static const Map<String, List<String>> stateDistricts = {
    'Odisha': [
      'Bargarh',
      'Sambalpur',
      'Puri',
      'Cuttack',
      'Khurda',
      'Ganjam',
      'Mayurbhanj',
      'Koraput',
      'Sonepur',
      'Balasore',
      'Sundargarh',
      'Kendrapara',
      'Other District',
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Udaipur',
      'Bikaner',
      'Kota',
      'Barmer',
      'Jaisalmer',
      'Ajmer',
      'Nagaur',
      'Other District',
    ],
    'Uttar Pradesh': [
      'Varanasi',
      'Lucknow',
      'Agra',
      'Moradabad',
      'Bhadohi',
      'Saharanpur',
      'Kannauj',
      'Gorakhpur',
      'Prayagraj',
      'Other District',
    ],
    'Gujarat': [
      'Kutch',
      'Ahmedabad',
      'Surat',
      'Rajkot',
      'Patan',
      'Surendranagar',
      'Vadodara',
      'Other District',
    ],
    'West Bengal': [
      'Bankura',
      'Nadia',
      'Birbhum',
      'Murshidabad',
      'Purulia',
      'Kolkata',
      'Hooghly',
      'Other District',
    ],
    'Madhya Pradesh': [
      'Chanderi',
      'Maheshwar',
      'Bhopal',
      'Indore',
      'Gwalior',
      'Dhar',
      'Bastar',
      'Other District',
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Paithan',
      'Kolhapur',
      'Nagpur',
      'Aurangabad',
      'Solapur',
      'Other District',
    ],
    'Karnataka': [
      'Mysuru',
      'Bengaluru',
      'Channapatna',
      'Ilkal',
      'Dharwad',
      'Bidar',
      'Other District',
    ],
    'Tamil Nadu': [
      'Kanchipuram',
      'Madurai',
      'Thanjavur',
      'Coimbatore',
      'Salem',
      'Chennai',
      'Other District',
    ],
    'Andhra Pradesh': [
      'Dharmavaram',
      'Mangalagiri',
      'Machilipatnam',
      'Srikalahasti',
      'Visakhapatnam',
      'Other District',
    ],
    'Bihar': [
      'Madhubani',
      'Bhagalpur',
      'Patna',
      'Gaya',
      'Muzaffarpur',
      'Other District',
    ],
    'Assam': [
      'Sualkuchi',
      'Kamrup',
      'Guwahati',
      'Barpeta',
      'Jorhat',
      'Other District',
    ],
    'Punjab': [
      'Amritsar',
      'Ludhiana',
      'Patiala',
      'Jalandhar',
      'Other District',
    ],
    'Kerala': [
      'Thrissur',
      'Balaramapuram',
      'Kozhikode',
      'Thiruvananthapuram',
      'Other District',
    ],
    'Other State': [
      'Central District',
      'North District',
      'South District',
      'East District',
      'West District',
      'Other',
    ],
  };

  static List<String> get states => stateDistricts.keys.toList();

  static List<String> getDistrictsForState(String state) {
    return stateDistricts[state] ?? ['Other District'];
  }
}
